<div class="alert alert-block alert-info">
    Import <b>Libraries</b>
</div>

<div class="alert alert-block alert-info">
    <b>1 . Data Collection</b>
    <br>
    <b>2 . Data Loading</b>
</div>

In [192]:
import pandas as pd
import numpy as np

In [193]:
df = pd.read_csv('data.csv')

df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0.0,0.0,3.0,1340.0,0.0,1955.0,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0.0,4.0,5.0,3370.0,280.0,1921.0,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0.0,0.0,4.0,1930.0,0.0,1966.0,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,NaN,NaN,NaN,1000.0,1000.0,1963.0,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,NaN,NaN,NaN,1140.0,800.0,1976.0,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0.0,0.0,4.0,1510.0,0.0,1954.0,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0.0,0.0,3.0,1460.0,0.0,1983.0,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0.0,0.0,3.0,3010.0,0.0,2009.0,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0.0,0.0,3.0,1070.0,1020.0,1974.0,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0.0,0.0,4.0,1490.0,0.0,1990.0,0,18717 SE 258th St,Covington,WA 98042,USA

<div class="alert alert-block alert-info">
    <b>3 . Data Exploration </b>
</div>

In [194]:
df.head(2)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.5,1340,7912,1.5,0.0,0.0,3.0,1340.0,0.0,1955.0,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.5,3650,9050,2.0,0.0,4.0,5.0,3370.0,280.0,1921.0,0,709 W Blaine St,Seattle,WA 98119,USA

In [195]:
df.tail(2)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
4598,2014-07-10 00:00:00,203400.0,4.0,2.0,2090,6630,1.0,0.0,0.0,3.0,1070.0,1020.0,1974.0,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,220600.0,3.0,2.5,1490,8102,2.0,0.0,0.0,4.0,1490.0,0.0,1990.0,0,18717 SE 258th St,Covington,WA 98042,USA

In [196]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4590.000000,4586.000000,4584.000000,4584.000000,4590.000000,4590.000000,4590.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512636,0.007196,0.241492,3.451571,1827.289978,312.275599,1970.816122,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538508,0.084532,0.779632,0.677439,862.709317,464.297463,29.738091,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [197]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4590 non-null   float64
 7   waterfront     4586 non-null   float64
 8   view           4584 non-null   float64
 9   condition      4584 non-null   float64
 10  sqft_above     4590 non-null   float64
 11  sqft_basement  4590 non-null   float64
 12  yr_built       4590 non-null   float64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(10), int64(3), object(5)
memory usage: 647.0+ KB

In [198]:
df.count()

date             4600
price            4600
bedrooms         4600
bathrooms        4600
sqft_living      4600
sqft_lot         4600
floors           4590
waterfront       4586
view             4584
condition        4584
sqft_above       4590
sqft_basement    4590
yr_built         4590
yr_renovated     4600
street           4600
city             4600
statezip         4600
country          4600
dtype: int64

In [199]:
df['price'].unique()

array([ 313000.      , 2384000.      ,  342000.      , ...,
        416904.166667,  203400.      ,  220600.      ], shape=(1741,))

In [200]:
df.nunique()

date               70
price            1741
bedrooms           10
bathrooms          26
sqft_living       566
sqft_lot         3113
floors              6
waterfront          2
view                5
condition           5
sqft_above        511
sqft_basement     207
yr_built          115
yr_renovated       60
street           4525
city               44
statezip           77
country             1
dtype: int64

In [201]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [202]:
# important function of preprocessing
df.isnull().sum()

date              0
price             0
bedrooms          0
bathrooms         0
sqft_living       0
sqft_lot          0
floors           10
waterfront       14
view             16
condition        16
sqft_above       10
sqft_basement    10
yr_built         10
yr_renovated      0
street            0
city              0
statezip          0
country           0
dtype: int64

<div class="alert alert-block alert-info">
    <b>4 . Data Preprocessing </b>
</div>

In [203]:
df.isnull().sum()

date              0
price             0
bedrooms          0
bathrooms         0
sqft_living       0
sqft_lot          0
floors           10
waterfront       14
view             16
condition        16
sqft_above       10
sqft_basement    10
yr_built         10
yr_renovated      0
street            0
city              0
statezip          0
country           0
dtype: int64

In [204]:
df['city'].isnull().sum()

np.int64(0)

In [205]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4590 non-null   float64
 7   waterfront     4586 non-null   float64
 8   view           4584 non-null   float64
 9   condition      4584 non-null   float64
 10  sqft_above     4590 non-null   float64
 11  sqft_basement  4590 non-null   float64
 12  yr_built       4590 non-null   float64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(10), int64(3), object(5)
memory usage: 647.0+ KB

In [206]:
df.date.unique()
df.country.unique()

array(['USA'], dtype=object)

In [207]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4590 non-null   float64
 7   waterfront     4586 non-null   float64
 8   view           4584 non-null   float64
 9   condition      4584 non-null   float64
 10  sqft_above     4590 non-null   float64
 11  sqft_basement  4590 non-null   float64
 12  yr_built       4590 non-null   float64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(10), int64(3), object(5)
memory usage: 647.0+ KB

<div class="alert alert-block alert-info">
    <b>5 . Manage null values </b>
</div>

In [208]:
df['floors'].mean
# df['floors'].median()
# df['floors'].mod()[0]

<bound method Series.mean of 0       1.5
1       2.0
2       1.0
3       1.0
4       1.0
       ...
4595    1.0
4596    2.0
4597    2.0
4598    1.0
4599    2.0
Name: floors, Length: 4600, dtype: float64>

In [209]:
# ' ' , N/A , None, Nan
df['floors'].fillna(df['floors'].mean(), inplace=True)

In [210]:
def fillNaFloatMean(columns):
    for i in columns:
        if df[i].dtype in ['float64', 'int64']:  # only numeric
            df[i].fillna(df[i].mean(), inplace=True)
            print(f"Filled NaN in {i} with mean: {df[i].mean()}")
        else:
            print(f"Skipped {i} (non-numeric type: {df[i].dtype})")

columns = ['price', 'sqft_lot', 'sqft_living', 'condition', 'sqft_above', 'sqft_basement']
fillNaFloatMean(columns)

Filled NaN in price with mean: 551962.9884732141
Filled NaN in sqft_lot with mean: 14852.516086956522
Filled NaN in sqft_living with mean: 2139.3469565217392
Filled NaN in condition with mean: 3.451570680628272
Filled NaN in sqft_above with mean: 1827.2899782135078
Filled NaN in sqft_basement with mean: 312.2755991285403

C:\Users\BURHAN ASGHAR\AppData\Local\Temp\ipykernel_2788\1870827581.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mean(), inplace=True)

In [211]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4586 non-null   float64
 8   view           4584 non-null   float64
 9   condition      4600 non-null   float64
 10  sqft_above     4600 non-null   float64
 11  sqft_basement  4600 non-null   float64
 12  yr_built       4590 non-null   float64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(10), int64(3), object(5)
memory usage: 647.0+ KB

<div class="alert alert-block alert-info">
    <b>6 . Manageing data types </b>
</div>

In [212]:
# df['price'] = df['price'].astype('int64')

def ChangeFloatToInt(cols):
    for i in cols:
        # print(type(df[i]))
        df[i] = df[i].astype('int64')

columns = ['sqft_lot', 'sqft_living', 'condition', 'sqft_above', 'sqft_basement', 'bedrooms',
           'bathrooms']

ChangeFloatToInt(columns)

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   int64
 3   bathrooms      4600 non-null   int64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4586 non-null   float64
 8   view           4584 non-null   float64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4590 non-null   float64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(5), int64(8), object(5)
memory usage: 647.0+ KB

In [214]:
# Convert specific object columns to integer (if numeric strings)

# Enter your object column names here
object_columns = ['date' , 'street' , 'city' ,'statezip' , 'country']  # e.g., ['sqft_living', 'price', 'sqft_lot']

for col in object_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')

print("Conversion completed. Columns converted to int:", object_columns)

Conversion completed. Columns converted to int: ['date', 'street', 'city', 'statezip', 'country']

In [215]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           0 non-null      Int64
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   int64
 3   bathrooms      4600 non-null   int64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4586 non-null   float64
 8   view           4584 non-null   float64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4590 non-null   float64
 13  yr_renovated   4600 non-null   int64
 14  street         0 non-null      Int64
 15  city           0 non-null      Int64
 16  statezip       0 non-null      Int64
 17  country        0 non-null      Int64
dtypes: Int64(5), float64(5), int64(8)
memory usage: 669.5 KB

In [216]:
# 🔍 Step 1: Find the problematic non-numeric values
float_columns = ['floors', 'waterfront', 'view', 'yr_built']

for col in float_columns:
    print(f"\n--- Checking {col} ---")
    bad_vals = df[~df[col].astype(str).str.replace('.', '', regex=False).str.isnumeric()][col].unique()
    print(bad_vals)

--- Checking floors ---
[]

--- Checking waterfront ---
[nan]

--- Checking view ---
[nan]

--- Checking yr_built ---
[nan]

In [217]:
for col in ['floors', 'waterfront', 'view', 'yr_built']:
    print(f"\n--- {col} ---")
    print(df[col].unique()[:20])  # show first 20 unique values

--- floors ---
[1.5        2.         1.         1.51263617 2.5        3.
 3.5       ]

--- waterfront ---
[ 0. nan  1.]

--- view ---
[ 0.  4. nan  1.  2.  3.]

--- yr_built ---
[1955. 1921. 1966. 1963. 1976. 1938.   nan 1997. 1987. 1983. 1923. 1954.
 2005. 1991. 1959. 1948. 1920. 1979. 1951. 1967.]

In [219]:
#  Safely convert object/float columns to integer (Int64)
float_columns = ['floors', 'waterfront', 'view', 'yr_built']

for col in float_columns:
    # Step 1: Force numeric conversion
    df[col] = pd.to_numeric(df[col], errors='coerce')

    # Step 2: Round values before int conversion (avoid float errors)
    df[col] = df[col].round(0)

    # Step 3: Convert to Int64 (supports NaN)
    df[col] = df[col].astype('Int64')

print("Successfully converted to Int64:", float_columns)
print(df[float_columns].dtypes)

Successfully converted to Int64: ['floors', 'waterfront', 'view', 'yr_built']
floors        Int64
waterfront    Int64
view          Int64
yr_built      Int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           0 non-null      Int64
 1   price          4600 non-null   int64
 2   bedrooms       4600 non-null   int64
 3   bathrooms      4600 non-null   int64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   Int64
 7   waterfront     4586 non-null   Int64
 8   view           4584 non-null   Int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4590 non-null   Int64
 13  yr_renovated   4600 non-null   int64
 14  street         0 non-null      Int64
 15  city           0 non-null      Int64
 16  statezip       0 non-null      Int64
 17  country        0 non-null      Int64
dtypes: Int64(9), int64(9)
memory usage: 687.4 KB

In [ ]:
# Convert all Int64 and int64 columns to plain int64 (standard lowercase)
for col in df.select_dtypes(include=['Int64', 'int64']).columns:
    df[col] = df[col].fillna(0).astype('int64')

print("All integer columns converted to standard int64:")
print(df.dtypes)

✅ All integer columns converted to standard int64:
date               int64
price            float64
bedrooms           int64
bathrooms          int64
sqft_living        int64
sqft_lot           int64
floors             int64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street             int64
city               int64
statezip           int64
country            int64
dtype: object

In [221]:
df['price'] = df['price'].fillna(0).astype('int64')

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   int64
 1   price          4600 non-null   int64
 2   bedrooms       4600 non-null   int64
 3   bathrooms      4600 non-null   int64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   int64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   int64
 15  city           4600 non-null   int64
 16  statezip       4600 non-null   int64
 17  country        4600 non-null   int64
dtypes: int64(18)
memory usage: 647.0 KB